# Generated by Django 5.2.8 on 2025-11-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPPORT', 'Suporte'), ('SPEAKER', 'Palestra'), ('FINANCE', 'Finanças'), ('FOLLOW_UP', 'Pós-encontro'), ('REGISTRATION', 'Fichas'), ('LOGISTICS', 'Montagem'), ('MEMBER', 'Membro')], default='MEMBER', max_length=30),
        ),
    ]
