# Generated by Django 3.2 on 2025-07-27 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_option', models.CharField(choices=[('Default', 'Padrão'), ('User', 'Usuários'), ('Permission', 'Permissões')], default='Default', max_length=50)),
                ('permission_read', models.BooleanField(default=False, verbose_name='Visualizar')),
                ('permission_write', models.BooleanField(default=False, verbose_name='Criar')),
                ('permission_update', models.BooleanField(default=False, verbose_name='Atualizar')),
                ('permission_delete', models.BooleanField(default=False, verbose_name='Apagar')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='profilepermissions',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_profile_permission_name'),
        ),
        migrations.AddField(
            model_name='permissionoptions',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='permission.profilepermissions'),
        ),
        migrations.AddConstraint(
            model_name='permissionoptions',
            constraint=models.UniqueConstraint(fields=('profile', 'app_option'), name='unique_permission_options_profile_app'),
        ),
    ]
